### ISSUE TITLE
Votes claimed but not credited when logging on at a later time

### ISSUE THREAD

**Issue by JamesTalon** [DeathTech154/VoteRewards#8]
I voted shortly after midnight this morning, my console picked up the voted and claimed it, but had me with a 0 balance when I logged on later after sleeping. Same thing happened to another player on my server.

Edit: I voted using steam, the other used username field.

**Comment by DeathTech154** [comment]
Will get it sorted in a few and release a new hotfix.

**Comment by JamesTalon** [comment]
Appears to be fixed with hotfix
