### ISSUE TITLE
People getting removed before 24 hours have passed.

### ISSUE THREAD

**Issue by DeathTech154** [DeathTech154/VoteRewards#9]
Bug reported by Kirthos via PM:
Players losing their voting stream after day X.

Cause: System using the poorly made method from ecoservers.io to tell if it's been 24 hours.

**Comment by DeathTech154** [comment]
Will be fixing in next hotfix by replacing code dependant on ecoservers.io for time confirmation to code that uses the in-game world time.

**Comment by JamesTalon** [comment]
I just came to post this issue. Looking forward to the next hotfix :D

**Comment by DeathTech154** [comment]
Haha yeah, I'm going to be removing the reliance on their system cause it's seemingly unreliable. XD

Will have to wait a little while though as I won't have time to work on the hotfix over the weekend. (Unless I'm cheeky and do it anyway.)

**Comment by DeathTech154** [comment]
Quick update, I've been busy working on the mod and have now removed the dependency on ecoservers.io to remove players, instead we are now using world time to determine when to remove players from the auto-update list. Hopefully, it will be better now.

**Comment by DeathTech154** [comment]
Closing issue.
Fixed.
